### PR TITLE
Day 2

### PR DESCRIPTION
**Pull request by jyantsss**
completed upto section 4

### CODE REVIEW

**Comment by prasantadh** [comment]
There are merge conflicts on the branch. Please address those and resubmit.

**Comment by prasantadh** [comment]
There is still a merge commit on the pull. Please fix and resubmit.

**Comment by jyantsss** [comment]
image

But here its showing no confilct. I'm confused how to solve.

**Comment by prasantadh** [comment]
Tei merge commits le garda hola. We can have a look once you have some time. Main issue is that it seems you are working on your own main branch.

**Comment by NoobGajen** [comment]
> image
> 
> But here its showing no confilct. I'm confused how to solve.

Your pull request cannot be accepted because your branch is `behind than the main branch of gajabaar repo`, and also has `multiple commit messages` which can't be accepted as far as i know, and you're `working from the main branch` which is not recommanded.

**Pull request closed without merging**
